import React from 'react';
import { Icon } from '../../lib/components.jsx';
import { usePhase } from '../state.jsx';
import { hilite } from '../../screens/shared.jsx';

function BRONZE_BODY(qual) {
  return `-- bronze.${qual}
-- Raw landing · system of record · zero transformation · append-only.
-- Source columns land as VARCHAR / VARIANT; ingestion pipeline appends
-- the standard lineage columns and partitions by _ingestion_date.
create or replace table bronze.${qual} (
  -- ...source columns land as VARCHAR / VARIANT...
  raw_payload     variant,                 -- full source JSON preserved alongside flattened columns
  _ingested_at    timestamp,               -- when the record entered Bronze
  _source         varchar,                 -- source system identifier
  _batch_id       varchar,                 -- pipeline run id for lineage
  _ingestion_date date as (date(_ingested_at)) -- partition key
)
cluster by (_ingestion_date, _source);

-- Promotion gate: Bronze is append-only. Replay is driven from
-- (_ingestion_date, _source, _batch_id). Updates and deletes are
-- never applied here — CDC deletes surface as tombstones in S1.`;
}

// ---------------------------------------------------------------------------
// S1 · Deduplication (Silver, sub-layer 1)
//
// The reviewer attestation is recorded in the view DDL header (promotion
// gate). The view emits TWO related projections: _s1_valid (records that
// passed dedup) and _s1_quarantine (null-natural-key rows). Only _s1_valid
// flows forward; quarantine remains visible for remediation.
// ---------------------------------------------------------------------------
const S1_BODY = `-- silver.s1_dedup.finance_ap_invoices_valid
-- Generated by dedup-builder-agent v1.2.0
-- Reviewed by dedup-reviewer-agent · attested 2026-05-17T18:42Z
-- Strategy: natural-key + CDC-aware. Tombstones retained as current record.
-- Promotion gate: feeds silver.s2_typecast.finance_ap_invoices on approval.

create or replace view silver.s1_dedup.finance_ap_invoices_valid as
with ranked as (
  select
    src.*,
    -- natural key declared in entity config; never hardcoded in the view
    src.invoice_id                                       as _dedup_key,
    'natural'                                            as _dedup_key_type,
    case
      when src.cdc_op is not null  then 'cdc'
      when count(*) over (partition by src.invoice_id, src._batch_id) > 1 then 'within_batch'
      else 'across_batch'
    end                                                  as _dedup_strategy,
    -- CDC DELETE surfaced as a tombstone record (never physically deleted)
    (src.cdc_op = 'DELETE')                              as _is_deleted,
    case when src.cdc_op = 'DELETE' then src.cdc_event_ts end as _deleted_at,
    row_number() over (
      partition by src.invoice_id
      -- late-arriving correctness: order by source event time first, then ingest time
      order by coalesce(src.cdc_event_ts, src._ingested_at) desc,
               hash(src.*)                               -- deterministic tie-break
    ) as _rn
  from bronze.ap.invoices src
  where src.invoice_id is not null
)
select * exclude (_rn, cdc_op, cdc_event_ts),
       true                              as _dedup_passed,
       cast(null as varchar)             as _dedup_failure_reason
  from ranked
 where _rn = 1;

create or replace view silver.s1_dedup.finance_ap_invoices_s1_quarantine as
select
  src.*,
  cast(null as varchar)         as _dedup_key,
  'natural'                     as _dedup_key_type,
  cast(null as varchar)         as _dedup_strategy,
  false                         as _is_deleted,
  cast(null as timestamp)       as _deleted_at,
  false                         as _dedup_passed,
  'null_natural_key'            as _dedup_failure_reason
from bronze.ap.invoices src
where src.invoice_id is null;`;

// ---------------------------------------------------------------------------
// S2 · Type-cast (Silver, sub-layer 2)
//
// Cast failures are schema contract violations, not DQ issues. Mandatory
// failures route to _s2_quarantine with a populated _cast_failure_reason.
// Optional cast failures NULL the cell and flag _cast_passed = FALSE but do
// NOT quarantine the row. S2 is a view; G1 is the single materialisation.
// ---------------------------------------------------------------------------
const S2_BODY = `-- silver.s2_typecast.finance_ap_invoices_valid
-- Generated by type-cast-builder-agent v1.2.0
-- Reviewed by type-cast-reviewer-agent · attested 2026-05-17T18:51Z
-- Money lands as NUMERIC(18,4) — never FLOAT.
-- Promotion gate: feeds silver.s3_cleanse.finance_ap_invoices on approval.

create or replace view silver.s2_typecast.finance_ap_invoices_valid as
with cast_attempts as (
  select
    src.*,
    try_cast(src.invoice_id    as varchar(32))   as t_invoice_id,    -- mandatory
    try_cast(src.vendor_id     as varchar(32))   as t_vendor_id,     -- optional
    -- date format declared in entity config; no auto-detect (MM/DD/YYYY for ERP)
    try_to_date(src.issue_date, 'MM/DD/YYYY')    as t_issue_date,    -- mandatory
    try_to_decimal(src.amount, 18, 4)            as t_amount,        -- mandatory · money
    upper(try_cast(src.currency as varchar(3)))  as t_currency,      -- optional
    -- boolean normalisation map · case-insensitive
    case lower(trim(src.is_active))
      when 'true'  then true  when '1' then true  when 'y' then true  when 'yes' then true  when 'on'  then true
      when 'false' then false when '0' then false when 'n' then false when 'no'  then false when 'off' then false
      else null
    end                                          as t_is_active,     -- mandatory
    src.status                                   as t_status         -- carried, cleansed in S3
  from silver.s1_dedup.finance_ap_invoices_valid src
),
classified as (
  select *,
    case
      when t_invoice_id is null then 'not_castable_varchar'
      when t_issue_date is null then 'not_a_date'
      when t_amount     is null then 'not_numeric'
      when t_is_active  is null and is_active is not null then 'unrecognised_boolean'
    end                                          as _cast_failure_reason,
    case
      when t_invoice_id is null then 'invoice_id'
      when t_issue_date is null then 'issue_date'
      when t_amount     is null then 'amount'
      when t_is_active  is null and is_active is not null then 'is_active'
    end                                          as _cast_failure_column
  from cast_attempts
)
select
  t_invoice_id   as invoice_id,
  t_vendor_id    as vendor_id,
  t_issue_date   as issue_date,
  t_amount       as amount,
  t_currency     as currency,
  t_is_active    as is_active,
  t_status       as status,
  -- pass-through: S1 dedup metadata + Bronze lineage
  _dedup_key, _dedup_key_type, _dedup_strategy, _is_deleted, _deleted_at,
  _ingested_at, _source, _batch_id, _ingestion_date,
  true                                            as _cast_passed,
  cast(null as varchar)                           as _cast_failure_column,
  cast(null as varchar)                           as _cast_failure_reason
from classified
where _cast_failure_reason is null;

create or replace view silver.s2_typecast.finance_ap_invoices_s2_quarantine as
-- Mandatory-column cast failures only. Optional failures stay on _s2_valid
-- with the cell NULL'd and _cast_passed flagged.
with cast_attempts as (
  select
    src.*,
    try_cast(src.invoice_id    as varchar(32))   as t_invoice_id,
    try_to_date(src.issue_date, 'MM/DD/YYYY')    as t_issue_date,
    try_to_decimal(src.amount, 18, 4)            as t_amount,
    case lower(trim(src.is_active))
      when 'true'  then true  when '1' then true  when 'y' then true  when 'yes' then true  when 'on'  then true
      when 'false' then false when '0' then false when 'n' then false when 'no'  then false when 'off' then false
      else null
    end                                          as t_is_active
  from silver.s1_dedup.finance_ap_invoices_valid src
)
select
  src.invoice_id, src.vendor_id, src.issue_date, src.amount, src.currency, src.is_active, src.status,
  src._dedup_key, src._dedup_key_type, src._dedup_strategy, src._is_deleted, src._deleted_at,
  src._ingested_at, src._source, src._batch_id, src._ingestion_date,
  false                  as _cast_passed,
  case
    when ca.t_invoice_id is null then 'invoice_id'
    when ca.t_issue_date is null then 'issue_date'
    when ca.t_amount     is null then 'amount'
    when ca.t_is_active  is null and src.is_active is not null then 'is_active'
  end                    as _cast_failure_column,
  case
    when ca.t_invoice_id is null then 'not_castable_varchar'
    when ca.t_issue_date is null then 'not_a_date'
    when ca.t_amount     is null then 'not_numeric'
    when ca.t_is_active  is null and src.is_active is not null then 'unrecognised_boolean'
  end                    as _cast_failure_reason
from silver.s1_dedup.finance_ap_invoices_valid src
join cast_attempts ca using (invoice_id)
where ca.t_invoice_id is null
   or ca.t_issue_date is null
   or ca.t_amount     is null
   or (ca.t_is_active is null and src.is_active is not null);`;

// ---------------------------------------------------------------------------
// S3 · Cleanse (Silver, sub-layer 3)
//
// Normalises semantically-inconsistent values to canonical form: sentinels
// to NULL, TRIM + case rules, control-character stripping, enum mapping via
// a reference table, phone E.164. Unmappable enums and invalid identifiers
// route to _s3_quarantine — they remain visible for remediation but do not
// flow to Gold.
// ---------------------------------------------------------------------------
const S3_BODY = `-- silver.s3_cleanse.finance_ap_invoices_valid
-- Generated by cleanse-builder-agent v1.2.0
-- Reviewed by cleanse-reviewer-agent · attested 2026-05-17T18:58Z
-- Promotion gate: feeds gold.g1.dim_invoice on approval.

create or replace view silver.s3_cleanse.finance_ap_invoices_valid as
with trimmed as (
  select
    -- TRIM + control-character stripping applied to every string column
    regexp_replace(trim(invoice_id),  '[\\\\x00-\\\\x1F\\\\x7F]', '') as invoice_id,
    regexp_replace(trim(vendor_id),   '[\\\\x00-\\\\x1F\\\\x7F]', '') as vendor_id,
    regexp_replace(trim(status),      '[\\\\x00-\\\\x1F\\\\x7F]', '') as status_raw,
    regexp_replace(trim(currency),    '[\\\\x00-\\\\x1F\\\\x7F]', '') as currency_raw,
    issue_date, amount, is_active,
    _dedup_key, _dedup_key_type, _dedup_strategy, _is_deleted, _deleted_at,
    _cast_passed, _cast_failure_column, _cast_failure_reason,
    _ingested_at, _source, _batch_id, _ingestion_date
  from silver.s2_typecast.finance_ap_invoices_valid
),
nulled as (
  -- empty strings, whitespace-only, and known sentinels → SQL NULL
  select
    case when invoice_id  in ('', 'N/A', 'NA', 'NULL', 'null', 'none', 'None', '-', '.') then null else invoice_id  end as invoice_id,
    case when vendor_id   in ('', 'N/A', 'NA', 'NULL', 'null', 'none', 'None', '-', '.') then null else vendor_id   end as vendor_id,
    case when status_raw  in ('', 'N/A', 'NA', 'NULL', 'null', 'none', 'None', '-', '.') then null else status_raw  end as status_raw,
    case when currency_raw in ('', 'N/A', 'NA', 'NULL', 'null')                          then null else currency_raw end as currency_raw,
    -- placeholder dates → NULL
    case when issue_date in (date '1900-01-01', date '9999-12-31', date '2099-12-31') then null else issue_date end as issue_date,
    amount, is_active,
    _dedup_key, _dedup_key_type, _dedup_strategy, _is_deleted, _deleted_at,
    _cast_passed, _cast_failure_column, _cast_failure_reason,
    _ingested_at, _source, _batch_id, _ingestion_date
  from trimmed
),
cased as (
  select
    upper(invoice_id)             as invoice_id,   -- UPPER · identifier code
    initcap(vendor_id)            as vendor_name,  -- INITCAP · proper name
    upper(currency_raw)           as currency,     -- UPPER · ISO-4217 code
    status_raw,                                    -- canonical-mapped below
    issue_date, amount, is_active,
    _dedup_key, _dedup_key_type, _dedup_strategy, _is_deleted, _deleted_at,
    _cast_passed, _cast_failure_column, _cast_failure_reason,
    _ingested_at, _source, _batch_id, _ingestion_date
  from nulled
),
enum_mapped as (
  -- Enum mapping via reference table · keyed by (source_system, field, raw_value)
  select
    c.*,
    coalesce(m.canonical_value, c.status_raw) as status,
    (m.canonical_value is not null)           as _cleanse_enum_mapped,
    case
      when c.status_raw is null then null
      when m.canonical_value is null
        and c.status_raw not in ('open', 'paid', 'void')
        then 'unmappable_enum'
    end                                       as _cleanse_quarantine_reason
  from cased c
  left join ref.enum_status m
    on  m.source_system = c._source
    and m.field_name    = 'status'
    and m.raw_value     = c.status_raw
)
select
  invoice_id, vendor_name, status, currency, issue_date, amount, is_active,
  _dedup_key, _dedup_key_type, _dedup_strategy, _is_deleted, _deleted_at,
  _cast_passed, _cast_failure_column, _cast_failure_reason,
  _ingested_at, _source, _batch_id, _ingestion_date,
  -- pipe-delimited list of cleansing rules applied to this record
  'trim|control_strip|sentinel_to_null|case_normalise|enum_map' as _cleanse_applied_rules,
  _cleanse_enum_mapped,
  cast(null as varchar) as _cleanse_quarantine_reason
from enum_mapped
where _cleanse_quarantine_reason is null;

create or replace view silver.s3_cleanse.finance_ap_invoices_s3_quarantine as
select
  invoice_id, vendor_name, status_raw as status, currency, issue_date, amount, is_active,
  _dedup_key, _dedup_key_type, _dedup_strategy, _is_deleted, _deleted_at,
  _cast_passed, _cast_failure_column, _cast_failure_reason,
  _ingested_at, _source, _batch_id, _ingestion_date,
  'trim|control_strip|sentinel_to_null|case_normalise|enum_map' as _cleanse_applied_rules,
  _cleanse_enum_mapped,
  _cleanse_quarantine_reason
from enum_mapped
where _cleanse_quarantine_reason is not null;`;

const TEST_DEDUP = `# tests/silver/test_dedup_grain.yaml
suite: dedup_grain
target: silver.s1_dedup.finance_ap_invoices_valid
assertions:
  - unique:
      columns: [invoice_id]
      where: "_is_deleted = false"   # tombstones are valid for their key
  - row_count_partition:
      against: bronze.ap.invoices
      buckets: [_dedup_strategy]      # within_batch / across_batch / cdc all sampled
      threshold: 0.05
  - quarantine_route:
      bad_rows_view: silver.s1_dedup.finance_ap_invoices_s1_quarantine
      reason_column: _dedup_failure_reason
      expected_reasons: [null_natural_key]
  - lineage_passthrough:
      columns: [_ingested_at, _source, _batch_id, _ingestion_date]`;

const TEST_QUAR = `# tests/silver/test_quarantine_routes.yaml
# Cast failures are schema contract violations, not DQ issues.
# Mandatory failures route to _s2_quarantine; optional failures NULL the cell.
suite: quarantine_routes
target: silver.s2_typecast.finance_ap_invoices_valid
assertions:
  - column_cast:
      column: amount
      type: numeric(18, 4)             # money — never FLOAT
  - column_cast:
      column: issue_date
      type: date
  - quarantine_route:
      bad_rows_view: silver.s2_typecast.finance_ap_invoices_s2_quarantine
      reason_column: _cast_failure_reason
      expected_reasons:
        - not_numeric
        - not_a_date
        - unrecognised_boolean
        - not_castable_varchar
  - mandatory_routing:
      column: amount
      classification: mandatory
      on_failure: quarantine
  - optional_cell_null_on_fail:
      column: vendor_id
      classification: optional
      on_failure: null_and_flag

---
# tests/silver/test_cleanse_rules.yaml
suite: cleanse_rules
target: silver.s3_cleanse.finance_ap_invoices_valid
assertions:
  - case_rule:
      column: currency
      rule: UPPER
  - case_rule:
      column: vendor_name
      rule: INITCAP
  - null_cleansing:
      columns: [invoice_id, status, currency]
      forbid_values: ["", " ", "N/A", "NA", "NULL", "-"]
  - enum_coverage:
      column: status
      mapping_table: ref.enum_status
      canonical_values: [open, paid, void]
      unmapped_routes_to: silver.s3_cleanse.finance_ap_invoices_s3_quarantine
  - phone_format:
      column: vendor_phone
      format: E.164
      invalid_routes_to: silver.s3_cleanse.finance_ap_invoices_s3_quarantine`;

const POLICY_BODY = `# policies/pii/finance_vendors.yaml
target: bronze.ap.vendors
masking:
  vendor_name:
    algorithm: sha256
    salt: env:VENDOR_SALT
retention:
  rows: 7y
  audit_log: true`;

const WALT_YAML = `# walt.yaml — project config
project: finance-platform
environments:
  - name: staging/dev
    promotes_to: main
  - name: main
agents:
  - ingestor
  - transformer
  - reasoner
  - operator
  - governer
schedules:
  ingestor:
    cadence: 30m
  transformer:
    cadence: on-event`;

const TREE = [
  { type: 'folder', name: 'bronze', children: [
    { type: 'folder', name: 'gl', children: [
      { type: 'file', name: 'journal_entries.sql', body: BRONZE_BODY('gl.journal_entries') },
      { type: 'file', name: 'gl_accounts.sql',     body: BRONZE_BODY('gl.gl_accounts') },
    ]},
    { type: 'folder', name: 'ap', children: [
      { type: 'file', name: 'invoices.sql', body: BRONZE_BODY('ap.invoices') },
      { type: 'file', name: 'vendors.sql',  body: BRONZE_BODY('ap.vendors') },
    ]},
    { type: 'folder', name: 'ar', children: [
      { type: 'file', name: 'invoices.sql',  body: BRONZE_BODY('ar.invoices') },
      { type: 'file', name: 'customers.sql', body: BRONZE_BODY('ar.customers') },
    ]},
  ]},
  { type: 'folder', name: 'silver', children: [
    { type: 'folder', name: 's1_dedup', children: [
      { type: 'file', name: 'finance_ap_invoices.sql', body: S1_BODY, active: true },
      { type: 'file', name: 'finance_ar_invoices.sql', body: '-- s1_dedup for ar.invoices' },
    ]},
    { type: 'folder', name: 's2_typecast', children: [
      { type: 'file', name: 'finance_ap_invoices.sql', body: S2_BODY },
    ]},
    { type: 'folder', name: 's3_cleanse', children: [
      { type: 'file', name: 'finance_ap_invoices.sql', body: S3_BODY },
    ]},
  ]},
  { type: 'folder', name: 'gold', children: [
    { type: 'file', name: 'fact_invoices.sql', body: '-- gold mart — generated when an analyst persona requests it' },
  ]},
  { type: 'folder', name: 'tests', children: [
    { type: 'file', name: 'test_dedup_grain.yaml',        body: TEST_DEDUP },
    { type: 'file', name: 'test_quarantine_routes.yaml',  body: TEST_QUAR },
  ]},
  { type: 'folder', name: 'policies', children: [
    { type: 'file', name: 'finance_vendors.yaml', body: POLICY_BODY },
  ]},
  { type: 'file', name: 'walt.yaml', body: WALT_YAML },
];

// Map the active silver stage to the file the user is reviewing. Used to focus
// the right file when the user opens this artifact during a review.
const STAGE_FILE = {
  s1: 'silver/s1_dedup/finance_ap_invoices.sql',
  s2: 'silver/s2_typecast/finance_ap_invoices.sql',
  s3: 'silver/s3_cleanse/finance_ap_invoices.sql',
};
const STAGE_LABEL = { s1: 'S1', s2: 'S2', s3: 'S3' };
const STAGE_EXPAND = {
  s1: { silver: true, s1_dedup: true },
  s2: { silver: true, s2_typecast: true },
  s3: { silver: true, s3_cleanse: true },
};

export function CodeArtifact() {
  const { ctx, shell } = usePhase();
  const branch = ctx?.branch || 'main';
  const committedTo = ctx?.gitConnected
    ? `${ctx.gitRemote || ctx.repoUrl || 'remote'} · ${branch}`
    : `local · ${branch}`;

  // If the user opened this artifact via a silver-code chip while a stage is
  // in review, surface that stage as the active file so they're reading the
  // exact code Walt is asking them to sign off on. Approval itself happens in
  // the chat — the side panel is information-only.
  const reviewStage = ctx?.silverStage && ['s1','s2','s3'].includes(ctx.silverStage)
    && shell?.silverStageStatus?.[ctx.silverStage] === 'review'
    && !ctx?.silverApproved?.[ctx.silverStage]
    ? ctx.silverStage
    : null;

  const initialActive = reviewStage ? STAGE_FILE[reviewStage] : 'silver/s1_dedup/finance_ap_invoices.sql';
  const initialExpanded = reviewStage ? STAGE_EXPAND[reviewStage] : { silver: true, s1_dedup: true };
  const [active, setActive] = React.useState(initialActive);
  const [expanded, setExpanded] = React.useState(initialExpanded);

  // When the review stage changes (e.g. S1 just flipped to 'review'), pivot the
  // tree to that stage's file so the bar always points at the right code.
  React.useEffect(() => {
    if (!reviewStage) return;
    setActive(STAGE_FILE[reviewStage]);
    setExpanded(e => ({ ...e, ...STAGE_EXPAND[reviewStage] }));
  }, [reviewStage]);

  const findFile = (nodes, path) => {
    for (const n of nodes) {
      if (n.type === 'file' && joinPath(n.__parent, n.name) === path) return n;
      if (n.type === 'folder') {
        const f = findFile(n.children.map(c => ({ ...c, __parent: joinPath(n.__parent, n.name) })), path);
        if (f) return f;
      }
    }
    return null;
  };

  const annotated = annotate(TREE, '');
  const current = findFile(annotated, active);
  const body = current?.body || '-- select a file';
  const isYaml = active.endsWith('.yaml');

  const toggle = (key) => setExpanded(e => ({ ...e, [key]: !e[key] }));

  return (
    <div style={{ display: 'flex', height: '100%', minHeight: 0 }}>
      <div style={{
        width: 260, flexShrink: 0,
        borderRight: '1px solid var(--border-subtle)',
        background: 'var(--bg-surface)',
        overflowY: 'auto',
        padding: '10px 8px 14px',
      }}>
        <div style={{
          padding: '4px 10px 8px',
          fontSize: 10.5, color: 'var(--text-muted)',
          textTransform: 'uppercase', letterSpacing: 0.5, fontWeight: 600,
        }}>
          finance-platform
        </div>
        <Tree nodes={annotated} expanded={expanded} active={active} onToggle={toggle} onPick={setActive}/>
      </div>

      <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', background: 'var(--code-bg)' }}>
        <div style={{
          padding: '8px 14px',
          borderBottom: '1px solid var(--border-subtle)',
          background: 'var(--bg-inset)',
          display: 'flex', alignItems: 'center', gap: 8,
          fontFamily: 'var(--font-mono)', fontSize: 11.5, color: 'var(--text-primary)',
        }}>
          <Icon name="file" size={11} color="var(--text-muted)"/>
          {active}
          <div style={{ flex: 1 }}/>
          <span style={{ fontSize: 10.5, color: 'var(--text-muted)' }}>read-only · committed to <span className="walt-mono">{committedTo}</span></span>
          <OpenInEditorMenu filePath={active} workspaceRoot={ctx?.localPath || '~/walt'}/>
        </div>

        {reviewStage && <ReviewStatusBanner stage={reviewStage}/>}

        <div style={{
          flex: 1, minHeight: 0, overflow: 'auto',
          padding: '14px 16px',
          fontFamily: 'var(--font-mono)',
          fontSize: 12, lineHeight: 1.65,
          color: 'var(--text-primary)',
          whiteSpace: 'pre',
        }}
        dangerouslySetInnerHTML={{ __html: isYaml ? escapeHtml(body) : hilite(body) }}
        />
      </div>
    </div>
  );
}

function joinPath(a, b) {
  if (!a) return b;
  return a + '/' + b;
}

function annotate(nodes, parent) {
  return nodes.map(n => ({
    ...n,
    __parent: parent,
    ...(n.children ? { children: annotate(n.children, joinPath(parent, n.name)) } : {}),
  }));
}

function Tree({ nodes, expanded, active, onToggle, onPick, depth = 0 }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column' }}>
      {nodes.map(n => {
        if (n.type === 'folder') {
          const open = expanded[n.name];
          return (
            <div key={joinPath(n.__parent, n.name)}>
              <button
                onClick={() => onToggle(n.name)}
                style={{
                  display: 'inline-flex', alignItems: 'center', gap: 6,
                  width: '100%', textAlign: 'left',
                  padding: '4px 8px', paddingLeft: 8 + depth * 12,
                  background: 'transparent', border: 'none',
                  fontSize: 12, color: 'var(--text-primary)',
                  fontFamily: 'var(--font-mono)', cursor: 'pointer',
                  borderRadius: 4,
                }}
              >
                <Icon name={open ? 'chevD' : 'chevR'} size={10} color="var(--text-muted)"/>
                <Icon name="folder" size={11} color="var(--accent)"/>
                {n.name}
              </button>
              {open && <Tree nodes={n.children} expanded={expanded} active={active} onToggle={onToggle} onPick={onPick} depth={depth + 1}/>}
            </div>
          );
        }
        const path = joinPath(n.__parent, n.name);
        const on = active === path;
        return (
          <button
            key={path}
            onClick={() => onPick(path)}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              width: '100%', textAlign: 'left',
              padding: '4px 8px', paddingLeft: 8 + depth * 12,
              background: on ? 'var(--accent-soft)' : 'transparent',
              border: 'none',
              fontSize: 12, color: on ? 'var(--accent)' : 'var(--text-secondary)',
              fontFamily: 'var(--font-mono)', cursor: 'pointer',
              borderRadius: 4,
              fontWeight: on ? 600 : 500,
            }}
          >
            <span style={{ width: 10 }}/>
            <Icon name="file" size={10} color={on ? 'var(--accent)' : 'var(--text-muted)'}/>
            {n.name}
          </button>
        );
      })}
    </div>
  );
}

// Passive status strip — shown above the code view when a silver stage is
// awaiting human approval. Information-only: this surface never accepts
// approvals. The user signs off in the chat using the Approve / Request-changes
// choices on the build task.
function ReviewStatusBanner({ stage }) {
  return (
    <div style={{
      padding: '8px 14px',
      borderBottom: '1px solid var(--border-subtle)',
      background: 'var(--accent-soft)',
      display: 'flex', alignItems: 'center', gap: 10,
      fontSize: 12, color: 'var(--text-primary)',
    }}>
      <span style={{
        display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
        width: 20, height: 20, borderRadius: 6,
        background: 'var(--accent)', color: 'var(--accent-on)',
        flexShrink: 0,
      }}>
        <Icon name="eye" size={10} color="currentColor"/>
      </span>
      <div style={{ display: 'flex', flexDirection: 'column', minWidth: 0, lineHeight: 1.35 }}>
        <div style={{ fontWeight: 600, color: 'var(--text-primary)' }}>
          Reviewing {STAGE_LABEL[stage]} code
        </div>
        <div style={{ fontSize: 11, color: 'var(--text-secondary)' }}>
          Read through the diff here, then approve or request changes in the chat.
        </div>
      </div>
    </div>
  );
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// ---- Open-in-editor menu -------------------------------------------------- //
// Each editor has its own URL handler. Clicking a row asks the OS to launch
// the editor at the given file. If the editor isn't installed locally the OS
// silently no-ops, which matches normal browser behaviour for unknown schemes.
const EDITORS = [
  { id: 'cursor',   label: 'Cursor',            scheme: 'cursor://file', icon: 'sparkle' },
  { id: 'vscode',   label: 'VS Code',           scheme: 'vscode://file', icon: 'code' },
  { id: 'vscodium', label: 'VSCodium',          scheme: 'vscodium://file', icon: 'code' },
  { id: 'idea',     label: 'JetBrains (IDEA)',  scheme: 'idea://open?file=', icon: 'bolt', encode: true },
  { id: 'fleet',    label: 'JetBrains Fleet',   scheme: 'fleet://file/',  icon: 'bolt' },
  { id: 'zed',      label: 'Zed',               scheme: 'zed://file',     icon: 'pulse' },
];

function OpenInEditorMenu({ filePath, workspaceRoot }) {
  const [open, setOpen] = React.useState(false);
  const ref = React.useRef(null);

  // Build an absolute(-looking) path the editor can resolve. We don't expand
  // `~` on the user's behalf — most editors accept it directly, and falling
  // back to the literal makes intent obvious if launching does fail.
  const root = (workspaceRoot || '~/walt').replace(/\/$/, '');
  const absPath = `${root}/${filePath}`;

  const buildHref = (ed) => {
    const target = ed.encode ? encodeURIComponent(absPath) : absPath;
    return `${ed.scheme}${target}`;
  };

  React.useEffect(() => {
    if (!open) return;
    const onClick = (e) => {
      if (ref.current && !ref.current.contains(e.target)) setOpen(false);
    };
    const onKey = (e) => { if (e.key === 'Escape') setOpen(false); };
    document.addEventListener('mousedown', onClick);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('mousedown', onClick);
      document.removeEventListener('keydown', onKey);
    };
  }, [open]);

  return (
    <div ref={ref} style={{ position: 'relative', display: 'inline-flex' }}>
      <button
        onClick={() => setOpen(o => !o)}
        title="Open this file in a local editor"
        style={{
          display: 'inline-flex', alignItems: 'center', gap: 5,
          padding: '3px 8px',
          borderRadius: 6,
          background: open ? 'var(--bg-hover)' : 'transparent',
          border: '1px solid ' + (open ? 'var(--border-strong)' : 'var(--border-subtle)'),
          color: 'var(--text-secondary)',
          fontSize: 11, fontFamily: 'var(--font-sans)', fontWeight: 500,
          cursor: 'pointer',
          transition: 'background .12s, border-color .12s',
        }}
      >
        <Icon name="code" size={10} color="currentColor"/>
        Open in editor
        <Icon name={open ? 'chevD' : 'chevR'} size={9} color="var(--text-muted)"/>
      </button>
      {open && (
        <div style={{
          position: 'absolute', top: 'calc(100% + 6px)', right: 0, zIndex: 20,
          background: 'var(--bg-surface)',
          border: '1px solid var(--border-default, var(--border-subtle))',
          borderRadius: 10,
          boxShadow: '0 12px 28px rgba(17,20,24,0.10), 0 2px 6px rgba(17,20,24,0.05)',
          padding: 4,
          minWidth: 220,
        }}>
          <div style={{
            padding: '6px 10px 8px',
            fontSize: 10.5, color: 'var(--text-muted)',
            textTransform: 'uppercase', letterSpacing: 0.5, fontWeight: 600,
          }}>Open file in…</div>
          {EDITORS.map(ed => (
            <a
              key={ed.id}
              href={buildHref(ed)}
              onClick={() => setOpen(false)}
              style={{
                display: 'flex', alignItems: 'center', gap: 10,
                padding: '7px 10px',
                borderRadius: 6,
                fontSize: 12, color: 'var(--text-primary)',
                textDecoration: 'none', cursor: 'pointer',
              }}
              onMouseEnter={(ev) => ev.currentTarget.style.background = 'var(--bg-hover)'}
              onMouseLeave={(ev) => ev.currentTarget.style.background = 'transparent'}
            >
              <span style={{
                width: 22, height: 22, borderRadius: 6,
                background: 'var(--bg-inset)',
                color: 'var(--text-secondary)',
                display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                flexShrink: 0,
              }}>
                <Icon name={ed.icon} size={11} color="currentColor"/>
              </span>
              <span style={{ flex: 1, minWidth: 0 }}>{ed.label}</span>
              <Icon name="arrowR" size={9} color="var(--text-muted)"/>
            </a>
          ))}
          <div style={{
            borderTop: '1px solid var(--border-subtle)',
            margin: '6px 4px 2px',
            padding: '6px 8px 4px',
            fontSize: 10.5, color: 'var(--text-muted)',
            lineHeight: 1.5,
          }}>
            Launches via the editor's URL handler. Falls back silently if the app isn't installed.
          </div>
        </div>
      )}
    </div>
  );
}
