import React from 'react';
import { Icon } from '../../lib/components.jsx';
import { usePhase } from '../state.jsx';
import { hilite } from '../../screens/shared.jsx';

function BRONZE_BODY(qual) {
  return `-- bronze.${qual}
-- 1:1 mirror of source · adds standard envelope columns
create or replace view bronze.${qual} as
select
  *,
  current_timestamp() as _ingested_at,
  'sql-erp01'         as _source,
  hash(now())         as _batch_id
from raw.${qual};`;
}

const S1_BODY = `-- silver.s1_dedup.finance_ap_invoices
-- generated by dedup-builder-agent v1.2.0
create or replace view silver.s1_dedup.finance_ap_invoices as
with ranked as (
  select *,
         row_number() over (
           partition by invoice_id
           order by _ingested_at desc, _batch_id desc
         ) as _rn
    from bronze.ap.invoices
)
select * exclude (_rn),
       current_timestamp() as _deduped_at
  from ranked
 where _rn = 1;`;

const S2_BODY = `-- silver.s2_typecast.finance_ap_invoices
-- generated by type-cast-builder-agent v1.2.0
create or replace view silver.s2_typecast.finance_ap_invoices as
select
  invoice_id::varchar(32)            as invoice_id,
  try_cast(vendor_id as varchar(32)) as vendor_id,
  try_to_date(issue_date)            as issue_date,
  try_to_decimal(amount, 18, 4)      as amount,
  upper(currency)::varchar(3)        as currency,
  status::varchar(16)                as status,
  _ingested_at, _source, _batch_id, _deduped_at
from silver.s1_dedup.finance_ap_invoices
where try_to_date(issue_date) is not null
  and try_to_decimal(amount, 18, 4) is not null;`;

const S3_BODY = `-- silver.s3_standardise.finance_ap_invoices
-- generated by standardisation-builder-agent v1.2.0
create or replace view silver.s3_standardise.finance_ap_invoices as
select
  invoice_id, vendor_id, issue_date, amount, currency,
  case
    when status in ('open','OPEN','o')         then 'open'
    when status in ('paid','PAID','p')         then 'paid'
    when status in ('void','VOID','cancelled') then 'void'
    else 'unknown'
  end as status,
  _ingested_at, _source, _batch_id, _deduped_at,
  current_timestamp() as _standardised_at
from silver.s2_typecast.finance_ap_invoices;`;

const TEST_DEDUP = `# tests/silver/test_dedup_grain.yaml
suite: dedup_grain
target: silver.s1_dedup.finance_ap_invoices
assertions:
  - unique:
      columns: [invoice_id]
  - row_count_drift:
      threshold: 0.05
      against: bronze.ap.invoices`;

const TEST_QUAR = `# tests/silver/test_quarantine_routes.yaml
suite: quarantine_routes
target: silver.s2_typecast.finance_ap_invoices
assertions:
  - relationship:
      type: quarantine
      bad_rows_table: quarantine.s2.finance_ap_invoices
  - column_cast:
      column: amount
      type: decimal(18,4)`;

const POLICY_BODY = `# policies/pii/finance_vendors.yaml
target: bronze.ap.vendors
masking:
  vendor_name:
    algorithm: sha256
    salt: env:VENDOR_SALT
retention:
  rows: 7y
  audit_log: true`;

const WALT_YAML = `# walt.yaml — project config
project: finance-platform
environments:
  - name: staging/dev
    promotes_to: main
  - name: main
agents:
  - ingestor
  - transformer
  - reasoner
  - operator
  - governer
schedules:
  ingestor:
    cadence: 30m
  transformer:
    cadence: on-event`;

const TREE = [
  { type: 'folder', name: 'bronze', children: [
    { type: 'folder', name: 'gl', children: [
      { type: 'file', name: 'journal_entries.sql', body: BRONZE_BODY('gl.journal_entries') },
      { type: 'file', name: 'gl_accounts.sql',     body: BRONZE_BODY('gl.gl_accounts') },
    ]},
    { type: 'folder', name: 'ap', children: [
      { type: 'file', name: 'invoices.sql', body: BRONZE_BODY('ap.invoices') },
      { type: 'file', name: 'vendors.sql',  body: BRONZE_BODY('ap.vendors') },
    ]},
    { type: 'folder', name: 'ar', children: [
      { type: 'file', name: 'invoices.sql',  body: BRONZE_BODY('ar.invoices') },
      { type: 'file', name: 'customers.sql', body: BRONZE_BODY('ar.customers') },
    ]},
  ]},
  { type: 'folder', name: 'silver', children: [
    { type: 'folder', name: 's1_dedup', children: [
      { type: 'file', name: 'finance_ap_invoices.sql', body: S1_BODY, active: true },
      { type: 'file', name: 'finance_ar_invoices.sql', body: '-- s1_dedup for ar.invoices' },
    ]},
    { type: 'folder', name: 's2_typecast', children: [
      { type: 'file', name: 'finance_ap_invoices.sql', body: S2_BODY },
    ]},
    { type: 'folder', name: 's3_standardise', children: [
      { type: 'file', name: 'finance_ap_invoices.sql', body: S3_BODY },
    ]},
  ]},
  { type: 'folder', name: 'gold', children: [
    { type: 'file', name: 'fact_invoices.sql', body: '-- gold mart — generated when an analyst persona requests it' },
  ]},
  { type: 'folder', name: 'tests', children: [
    { type: 'file', name: 'test_dedup_grain.yaml',        body: TEST_DEDUP },
    { type: 'file', name: 'test_quarantine_routes.yaml',  body: TEST_QUAR },
  ]},
  { type: 'folder', name: 'policies', children: [
    { type: 'file', name: 'finance_vendors.yaml', body: POLICY_BODY },
  ]},
  { type: 'file', name: 'walt.yaml', body: WALT_YAML },
];

export function CodeArtifact() {
  const { ctx } = usePhase();
  const branch = ctx?.branch || 'main';
  const committedTo = ctx?.gitConnected
    ? `${ctx.gitRemote || ctx.repoUrl || 'remote'} · ${branch}`
    : `local · ${branch}`;
  const [active, setActive] = React.useState('silver/s1_dedup/finance_ap_invoices.sql');
  const [expanded, setExpanded] = React.useState({ silver: true, s1_dedup: true });

  const findFile = (nodes, path) => {
    for (const n of nodes) {
      if (n.type === 'file' && joinPath(n.__parent, n.name) === path) return n;
      if (n.type === 'folder') {
        const f = findFile(n.children.map(c => ({ ...c, __parent: joinPath(n.__parent, n.name) })), path);
        if (f) return f;
      }
    }
    return null;
  };

  const annotated = annotate(TREE, '');
  const current = findFile(annotated, active);
  const body = current?.body || '-- select a file';
  const isYaml = active.endsWith('.yaml');

  const toggle = (key) => setExpanded(e => ({ ...e, [key]: !e[key] }));

  return (
    <div style={{ display: 'flex', height: '100%', minHeight: 0 }}>
      <div style={{
        width: 260, flexShrink: 0,
        borderRight: '1px solid var(--border-subtle)',
        background: 'var(--bg-surface)',
        overflowY: 'auto',
        padding: '10px 8px 14px',
      }}>
        <div style={{
          padding: '4px 10px 8px',
          fontSize: 10.5, color: 'var(--text-muted)',
          textTransform: 'uppercase', letterSpacing: 0.5, fontWeight: 600,
        }}>
          finance-platform
        </div>
        <Tree nodes={annotated} expanded={expanded} active={active} onToggle={toggle} onPick={setActive}/>
      </div>

      <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', background: 'var(--code-bg)' }}>
        <div style={{
          padding: '8px 14px',
          borderBottom: '1px solid var(--border-subtle)',
          background: 'var(--bg-inset)',
          display: 'flex', alignItems: 'center', gap: 8,
          fontFamily: 'var(--font-mono)', fontSize: 11.5, color: 'var(--text-primary)',
        }}>
          <Icon name="file" size={11} color="var(--text-muted)"/>
          {active}
          <div style={{ flex: 1 }}/>
          <span style={{ fontSize: 10.5, color: 'var(--text-muted)' }}>read-only · committed to <span className="walt-mono">{committedTo}</span></span>
          <OpenInEditorMenu filePath={active} workspaceRoot={ctx?.localPath || '~/walt'}/>
        </div>
        <div style={{
          flex: 1, minHeight: 0, overflow: 'auto',
          padding: '14px 16px',
          fontFamily: 'var(--font-mono)',
          fontSize: 12, lineHeight: 1.65,
          color: 'var(--text-primary)',
          whiteSpace: 'pre',
        }}
        dangerouslySetInnerHTML={{ __html: isYaml ? escapeHtml(body) : hilite(body) }}
        />
      </div>
    </div>
  );
}

function joinPath(a, b) {
  if (!a) return b;
  return a + '/' + b;
}

function annotate(nodes, parent) {
  return nodes.map(n => ({
    ...n,
    __parent: parent,
    ...(n.children ? { children: annotate(n.children, joinPath(parent, n.name)) } : {}),
  }));
}

function Tree({ nodes, expanded, active, onToggle, onPick, depth = 0 }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column' }}>
      {nodes.map(n => {
        if (n.type === 'folder') {
          const open = expanded[n.name];
          return (
            <div key={joinPath(n.__parent, n.name)}>
              <button
                onClick={() => onToggle(n.name)}
                style={{
                  display: 'inline-flex', alignItems: 'center', gap: 6,
                  width: '100%', textAlign: 'left',
                  padding: '4px 8px', paddingLeft: 8 + depth * 12,
                  background: 'transparent', border: 'none',
                  fontSize: 12, color: 'var(--text-primary)',
                  fontFamily: 'var(--font-mono)', cursor: 'pointer',
                  borderRadius: 4,
                }}
              >
                <Icon name={open ? 'chevD' : 'chevR'} size={10} color="var(--text-muted)"/>
                <Icon name="folder" size={11} color="var(--accent)"/>
                {n.name}
              </button>
              {open && <Tree nodes={n.children} expanded={expanded} active={active} onToggle={onToggle} onPick={onPick} depth={depth + 1}/>}
            </div>
          );
        }
        const path = joinPath(n.__parent, n.name);
        const on = active === path;
        return (
          <button
            key={path}
            onClick={() => onPick(path)}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              width: '100%', textAlign: 'left',
              padding: '4px 8px', paddingLeft: 8 + depth * 12,
              background: on ? 'var(--accent-soft)' : 'transparent',
              border: 'none',
              fontSize: 12, color: on ? 'var(--accent)' : 'var(--text-secondary)',
              fontFamily: 'var(--font-mono)', cursor: 'pointer',
              borderRadius: 4,
              fontWeight: on ? 600 : 500,
            }}
          >
            <span style={{ width: 10 }}/>
            <Icon name="file" size={10} color={on ? 'var(--accent)' : 'var(--text-muted)'}/>
            {n.name}
          </button>
        );
      })}
    </div>
  );
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// ---- Open-in-editor menu -------------------------------------------------- //
// Each editor has its own URL handler. Clicking a row asks the OS to launch
// the editor at the given file. If the editor isn't installed locally the OS
// silently no-ops, which matches normal browser behaviour for unknown schemes.
const EDITORS = [
  { id: 'cursor',   label: 'Cursor',            scheme: 'cursor://file', icon: 'sparkle' },
  { id: 'vscode',   label: 'VS Code',           scheme: 'vscode://file', icon: 'code' },
  { id: 'vscodium', label: 'VSCodium',          scheme: 'vscodium://file', icon: 'code' },
  { id: 'idea',     label: 'JetBrains (IDEA)',  scheme: 'idea://open?file=', icon: 'bolt', encode: true },
  { id: 'fleet',    label: 'JetBrains Fleet',   scheme: 'fleet://file/',  icon: 'bolt' },
  { id: 'zed',      label: 'Zed',               scheme: 'zed://file',     icon: 'pulse' },
];

function OpenInEditorMenu({ filePath, workspaceRoot }) {
  const [open, setOpen] = React.useState(false);
  const ref = React.useRef(null);

  // Build an absolute(-looking) path the editor can resolve. We don't expand
  // `~` on the user's behalf — most editors accept it directly, and falling
  // back to the literal makes intent obvious if launching does fail.
  const root = (workspaceRoot || '~/walt').replace(/\/$/, '');
  const absPath = `${root}/${filePath}`;

  const buildHref = (ed) => {
    const target = ed.encode ? encodeURIComponent(absPath) : absPath;
    return `${ed.scheme}${target}`;
  };

  React.useEffect(() => {
    if (!open) return;
    const onClick = (e) => {
      if (ref.current && !ref.current.contains(e.target)) setOpen(false);
    };
    const onKey = (e) => { if (e.key === 'Escape') setOpen(false); };
    document.addEventListener('mousedown', onClick);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('mousedown', onClick);
      document.removeEventListener('keydown', onKey);
    };
  }, [open]);

  return (
    <div ref={ref} style={{ position: 'relative', display: 'inline-flex' }}>
      <button
        onClick={() => setOpen(o => !o)}
        title="Open this file in a local editor"
        style={{
          display: 'inline-flex', alignItems: 'center', gap: 5,
          padding: '3px 8px',
          borderRadius: 6,
          background: open ? 'var(--bg-hover)' : 'transparent',
          border: '1px solid ' + (open ? 'var(--border-strong)' : 'var(--border-subtle)'),
          color: 'var(--text-secondary)',
          fontSize: 11, fontFamily: 'var(--font-sans)', fontWeight: 500,
          cursor: 'pointer',
          transition: 'background .12s, border-color .12s',
        }}
      >
        <Icon name="code" size={10} color="currentColor"/>
        Open in editor
        <Icon name={open ? 'chevD' : 'chevR'} size={9} color="var(--text-muted)"/>
      </button>
      {open && (
        <div style={{
          position: 'absolute', top: 'calc(100% + 6px)', right: 0, zIndex: 20,
          background: 'var(--bg-surface)',
          border: '1px solid var(--border-default, var(--border-subtle))',
          borderRadius: 10,
          boxShadow: '0 12px 28px rgba(17,20,24,0.10), 0 2px 6px rgba(17,20,24,0.05)',
          padding: 4,
          minWidth: 220,
        }}>
          <div style={{
            padding: '6px 10px 8px',
            fontSize: 10.5, color: 'var(--text-muted)',
            textTransform: 'uppercase', letterSpacing: 0.5, fontWeight: 600,
          }}>Open file in…</div>
          {EDITORS.map(ed => (
            <a
              key={ed.id}
              href={buildHref(ed)}
              onClick={() => setOpen(false)}
              style={{
                display: 'flex', alignItems: 'center', gap: 10,
                padding: '7px 10px',
                borderRadius: 6,
                fontSize: 12, color: 'var(--text-primary)',
                textDecoration: 'none', cursor: 'pointer',
              }}
              onMouseEnter={(ev) => ev.currentTarget.style.background = 'var(--bg-hover)'}
              onMouseLeave={(ev) => ev.currentTarget.style.background = 'transparent'}
            >
              <span style={{
                width: 22, height: 22, borderRadius: 6,
                background: 'var(--bg-inset)',
                color: 'var(--text-secondary)',
                display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                flexShrink: 0,
              }}>
                <Icon name={ed.icon} size={11} color="currentColor"/>
              </span>
              <span style={{ flex: 1, minWidth: 0 }}>{ed.label}</span>
              <Icon name="arrowR" size={9} color="var(--text-muted)"/>
            </a>
          ))}
          <div style={{
            borderTop: '1px solid var(--border-subtle)',
            margin: '6px 4px 2px',
            padding: '6px 8px 4px',
            fontSize: 10.5, color: 'var(--text-muted)',
            lineHeight: 1.5,
          }}>
            Launches via the editor's URL handler. Falls back silently if the app isn't installed.
          </div>
        </div>
      )}
    </div>
  );
}
