import React from 'react';
import { Icon } from '../../lib/components.jsx';
import { usePhase } from '../state.jsx';
import { AgentBadge, AgentAvatar } from '../components/AgentBadge.jsx';
import { ReviewChecklist } from '../components/ReviewChecklist.jsx';
import { SUB_AGENTS } from '../agents.js';
import { hilite } from '../../screens/shared.jsx';

const STAGES = [
  {
    key: 's1',
    summary: 'Deduplicate sources on declared grain, stamp dedup metadata.',
    code: `-- silver.s1_dedup.finance_ap_invoices
-- generated by dedup-builder-agent v1.2.0
create or replace view silver.s1_dedup.finance_ap_invoices as
with ranked as (
  select *,
         row_number() over (
           partition by invoice_id
           order by _ingested_at desc, _batch_id desc
         ) as _rn
    from bronze.ap.invoices
)
select * exclude (_rn),
       current_timestamp() as _deduped_at
  from ranked
 where _rn = 1;`,
    checks: {
      contract: 'pass', lineage: 'pass', quarantine: 'pass',
      noBleed: 'pass', naming: 'pass', metadata: 'pass', idempotency: 'pass',
    },
    rounds: 1,
    rowParity: 'bronze 186,402 → silver 184,917 · 1,485 dupes removed (cf. expected 1,200-1,800) · ok',
  },
  {
    key: 's2',
    summary: 'Cast columns to declared types; quarantine bad rows.',
    code: `-- silver.s2_typecast.finance_ap_invoices
-- generated by type-cast-builder-agent v1.2.0
create or replace view silver.s2_typecast.finance_ap_invoices as
select
  invoice_id::varchar(32)               as invoice_id,
  try_cast(vendor_id as varchar(32))    as vendor_id,
  try_to_date(issue_date)               as issue_date,
  try_to_decimal(amount, 18, 4)         as amount,
  upper(currency)::varchar(3)           as currency,
  status::varchar(16)                   as status,
  _ingested_at, _source, _batch_id, _ingestion_date,
  _deduped_at
from silver.s1_dedup.finance_ap_invoices
where try_to_date(issue_date) is not null
  and try_to_decimal(amount, 18, 4) is not null;`,
    checks: {
      contract: 'pass', lineage: 'pass', quarantine: 'fail',
      noBleed: 'pass', naming: 'pass', metadata: 'pass', idempotency: 'pass',
    },
    rounds: 2,
    rowParity: 'reviewer flagged: 14 rows fail amount cast — quarantine route missing. Builder retrying with quarantine.s2.finance_ap_invoices.',
  },
  {
    key: 's3',
    summary: 'Standardise enums, units, country/currency codes.',
    code: `-- silver.s3_standardise.finance_ap_invoices
-- generated by standardisation-builder-agent v1.2.0
create or replace view silver.s3_standardise.finance_ap_invoices as
select
  invoice_id,
  vendor_id,
  issue_date,
  amount,
  currency,                                   -- already iso-4217
  case
    when status in ('open','OPEN','o')        then 'open'
    when status in ('paid','PAID','p')        then 'paid'
    when status in ('void','VOID','cancelled') then 'void'
    else 'unknown'
  end                                         as status,
  _ingested_at, _source, _batch_id, _ingestion_date,
  _deduped_at,
  current_timestamp() as _standardised_at
from silver.s2_typecast.finance_ap_invoices;`,
    checks: {
      contract: 'pending', lineage: 'pending', quarantine: 'pending',
      noBleed: 'pending', naming: 'pending', metadata: 'pending', idempotency: 'pending',
    },
    rounds: 0,
    rowParity: '—',
  },
];

export function SilverBuildArtifact() {
  const { ctx, shell } = usePhase();
  // Active stage is driven by ctx.silverStage which the chat script controls. The
  // user can also click the stepper to peek at past stages — that's a local override
  // (peekIdx). When peek is null, we follow ctx.silverStage.
  const stageStatus = shell.silverStageStatus || { s1: 'idle', s2: 'idle', s3: 'idle' };
  const approvals = ctx.silverApproved || { s1: false, s2: false, s3: false };
  const activeStageKey = ctx.silverStage && ctx.silverStage !== 'idle' && ctx.silverStage !== 'done'
    ? ctx.silverStage
    : 's1';
  const activeStageIdx = Math.max(0, STAGES.findIndex(s => s.key === activeStageKey));

  const [peekIdx, setPeekIdx] = React.useState(null);
  const stageIdx = peekIdx != null ? peekIdx : activeStageIdx;

  // Reset peek when the active stage advances — auto-focus the new stage.
  React.useEffect(() => { setPeekIdx(null); }, [activeStageKey]);

  const stage = STAGES[stageIdx];
  const sub = SUB_AGENTS[stage.key];
  const currentStageStatus = stageStatus[stage.key] || 'idle';
  // For S2/S3 we mark the prior stage as 'approved' via ctx, so reflect that on the
  // status pill (otherwise the stepper would show "idle" on already-approved stages).
  const displayStatus = approvals[stage.key]
    ? 'approved'
    : currentStageStatus;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', minHeight: 0 }}>
      <div style={{
        padding: '12px 22px',
        borderBottom: '1px solid var(--border-subtle)',
        background: 'var(--bg-surface)',
        display: 'flex', alignItems: 'center', gap: 14,
      }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 13.5, fontWeight: 600, color: 'var(--text-primary)' }}>Silver build · finance_ap_invoices</div>
          <div style={{ fontSize: 11.5, color: 'var(--text-muted)', marginTop: 2, display: 'flex', alignItems: 'center', gap: 6 }}>
            <AgentBadge agent="transformer" size="sm"/> running 3 sub-layers · reviewer-gated
          </div>
        </div>
        <SilverStepper
          stageIdx={stageIdx}
          activeStageIdx={activeStageIdx}
          approvals={approvals}
          stageStatus={stageStatus}
          onJump={(i) => setPeekIdx(i === activeStageIdx ? null : i)}
        />
      </div>

      <div style={{ flex: 1, minHeight: 0, display: 'flex' }}>
        {/* Code preview */}
        <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', borderRight: '1px solid var(--border-subtle)' }}>
          <div style={{
            padding: '10px 14px',
            borderBottom: '1px solid var(--border-subtle)',
            display: 'flex', alignItems: 'center', gap: 10,
            background: 'var(--bg-inset)',
          }}>
            <AgentAvatar agent="transformer" size={22}/>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-primary)' }}>{sub.label}</div>
              <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>{stage.summary}</div>
            </div>
            <span style={{
              fontSize: 10, padding: '2px 7px', borderRadius: 999,
              background: 'var(--bg-elevated)', color: 'var(--text-secondary)',
              fontFamily: 'var(--font-mono)',
            }}>{sub.builder}</span>
          </div>
          <div style={{
            flex: 1, minHeight: 0, overflow: 'auto',
            padding: '12px 16px',
            background: 'var(--code-bg)',
            fontFamily: 'var(--font-mono)',
            fontSize: 12, lineHeight: 1.65,
            color: 'var(--text-primary)',
            whiteSpace: 'pre',
          }}
          dangerouslySetInnerHTML={{ __html: hilite(stage.code) }}
          />
          <div style={{
            padding: '8px 14px',
            borderTop: '1px solid var(--border-subtle)',
            display: 'flex', alignItems: 'center', gap: 10,
            fontSize: 11.5, color: 'var(--text-secondary)',
            background: 'var(--bg-inset)',
          }}>
            <Icon name="check" size={11} color="var(--status-ok)"/>
            <span>{stage.rowParity}</span>
          </div>
        </div>

        {/* Reviewer rail */}
        <div style={{
          width: 320, flexShrink: 0,
          background: 'var(--bg-app)',
          padding: 14, overflow: 'auto',
          display: 'flex', flexDirection: 'column', gap: 12,
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <AgentAvatar agent="transformer" size={22}/>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-primary)' }}>Reviewer agent</div>
              <div className="walt-mono" style={{ fontSize: 10.5, color: 'var(--text-muted)' }}>{sub.reviewer}</div>
            </div>
          </div>

          <ReviewChecklist states={stage.checks} roundTrips={stage.rounds || 1} maxRoundTrips={3}/>

          {stage.key === 's2' && (
            <div style={{
              background: 'rgba(192,57,79,0.08)',
              border: '1px solid color-mix(in srgb, var(--status-err) 25%, transparent)',
              color: 'var(--status-err)',
              borderRadius: 8, padding: 10,
              fontSize: 11.5, lineHeight: 1.5,
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontWeight: 600, marginBottom: 4 }}>
                <Icon name="x" size={10} color="var(--status-err)"/> Quarantine route missing
              </div>
              14 rows fail amount cast. Builder is on round 2 — adding <span className="walt-mono">quarantine.s2.finance_ap_invoices</span>.
            </div>
          )}

          {stage.key === 's3' && (
            <div style={{
              background: 'var(--bg-inset)',
              border: '1px solid var(--border-subtle)',
              borderRadius: 8, padding: 10,
              fontSize: 11.5, lineHeight: 1.5, color: 'var(--text-secondary)',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontWeight: 600, marginBottom: 4, color: 'var(--text-primary)' }}>
                <Icon name="clock" size={10} color="var(--text-muted)"/> Awaiting builder output
              </div>
              Builder is generating the standardisation view. Reviewer kicks in when DDL is committed.
            </div>
          )}

          <StageGateBanner status={displayStatus} stageKey={stage.key}/>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            <button className="walt-btn ghost sm">
              <Icon name="msg" size={10}/> Comment in DDL header
            </button>
            <button className="walt-btn ghost sm">
              <Icon name="refresh" size={10}/> Request builder retry
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function SilverStepper({ stageIdx, activeStageIdx, approvals, stageStatus, onJump }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
      {STAGES.map((s, i) => {
        const sub = SUB_AGENTS[s.key];
        const looking = i === stageIdx;
        const isActive = i === activeStageIdx;
        const done = approvals[s.key];
        const status = stageStatus[s.key] || 'idle';
        return (
          <React.Fragment key={s.key}>
            {i > 0 && <span style={{ width: 12, height: 1, background: 'var(--border-default)' }}/>}
            <button
              onClick={() => onJump(i)}
              style={{
                display: 'inline-flex', alignItems: 'center', gap: 5,
                padding: '4px 9px',
                borderRadius: 999,
                border: looking ? '1px solid var(--accent)' : '1px solid var(--border-subtle)',
                background: looking ? 'var(--accent-soft)' : 'var(--bg-surface)',
                fontSize: 11.5, fontWeight: 500,
                color: looking ? 'var(--accent)' : 'var(--text-secondary)',
                cursor: 'pointer',
                fontFamily: 'var(--font-sans)',
              }}
            >
              <span style={{
                width: 13, height: 13, borderRadius: 999,
                background: done ? 'var(--status-ok)'
                  : isActive ? 'var(--accent)'
                  : status === 'review' ? 'var(--accent)'
                  : 'var(--border-default)',
                color: 'white',
                display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 9, fontWeight: 600,
                position: 'relative',
              }}>
                {done ? <Icon name="check" size={7} color="white"/> : (i + 1)}
                {(status === 'running' && !done) && (
                  <span style={{
                    position: 'absolute', inset: -3, borderRadius: 999,
                    border: '1px solid var(--accent)', opacity: 0.5,
                    animation: 'walt-ring 1.8s ease-out infinite',
                    pointerEvents: 'none',
                  }}/>
                )}
              </span>
              {sub.label.split(' · ')[1] || sub.label}
            </button>
          </React.Fragment>
        );
      })}
    </div>
  );
}

// Banner inside the reviewer rail that mirrors the chat-driven gate state. The actual
// approval happens in chat ("Approve S1" pill); this just communicates *where* the
// flow is so the user understands what's blocking.
function StageGateBanner({ status, stageKey }) {
  if (status === 'approved') {
    return (
      <div style={{
        background: 'rgba(63,143,63,0.10)',
        border: '1px solid color-mix(in srgb, var(--status-ok) 25%, transparent)',
        color: 'var(--status-ok)',
        borderRadius: 8, padding: 10,
        fontSize: 11.5, lineHeight: 1.5,
        display: 'flex', alignItems: 'center', gap: 6, fontWeight: 600,
      }}>
        <Icon name="check" size={11} color="var(--status-ok)"/>
        {stageKey.toUpperCase()} approved — staged on the silver feature branch.
      </div>
    );
  }
  if (status === 'review') {
    return (
      <div className="walt-pop-in" style={{
        background: 'var(--accent-soft)',
        border: '1px solid color-mix(in srgb, var(--accent) 30%, transparent)',
        color: 'var(--accent)',
        borderRadius: 8, padding: 10,
        fontSize: 11.5, lineHeight: 1.5,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontWeight: 600, marginBottom: 3 }}>
          <Icon name="check" size={11} color="var(--accent)"/> {stageKey.toUpperCase()} ready for your review
        </div>
        <span style={{ color: 'var(--text-secondary)' }}>
          Look over the code + checks. Approve in the chat to continue.
        </span>
      </div>
    );
  }
  if (status === 'running') {
    return (
      <div style={{
        background: 'var(--bg-inset)',
        border: '1px solid var(--border-subtle)',
        borderRadius: 8, padding: 10,
        fontSize: 11.5, lineHeight: 1.5, color: 'var(--text-secondary)',
        display: 'flex', alignItems: 'center', gap: 6,
      }}>
        <span className="walt-dot run" style={{ width: 7, height: 7 }}/>
        Builder + reviewer running on {stageKey.toUpperCase()}…
      </div>
    );
  }
  return (
    <div style={{
      background: 'var(--bg-inset)',
      border: '1px solid var(--border-subtle)',
      borderRadius: 8, padding: 10,
      fontSize: 11.5, lineHeight: 1.5, color: 'var(--text-muted)',
    }}>
      {stageKey.toUpperCase()} hasn't started yet.
    </div>
  );
}
